USE EF6CodeFirst GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('adham','ruoss','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('albrecht','macconnal','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('aleksandr','baser','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('ally','challin','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('amelie','showell','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('ardine','cammish','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('ario','beine','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('aubrey','cushelly','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('bearnard','tames','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('bentlee','durrance','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('bobette','bartolomucci','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('bordy','hummerston','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('brady','groocock','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('brenna','managh','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('brit','watt','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('brittani','tilio','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('chas','ditch','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('chick','soper','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('christin','gunderson','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('claire','cribbin','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('cori','o''hogertie','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('cynthea','blodgett','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('cynthie','parram','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('dalis','eden','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('danya','o''boyle','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('deirdre','fane','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('dickie','keenor','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('dominik','heyball','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('donal','keslake','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('edee','nesbitt','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('edgardo','dakhno','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('elayne','gilbank','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('elden','durrance','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('erna','yeaman','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('ethelind','matyja','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('eugenie','chatelain','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('franni','pipping','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('gail','grimbaldeston','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('gerhard','guiso','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('gideon','goodlake','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('godiva','vinsen','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('grover','milley','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('halie','brockie','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('harp','hadcock','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('hartley','sproston','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('haven','berford','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('herb','anniwell','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('herbert','macpharlain','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('hernando','paxeford','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('hube','bum','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('idaline','laidlaw','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('irena','segges','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('isis','bradick','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('israel','gannicleff','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('jared','davenall','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('johannah','leghorn','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('katleen','lawlan','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('kerstin','beaumont','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('kimberlee','chestney','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('kirby','janc','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('korey','mackney','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('kris','womersley','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('lacee','ferrand','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('lanae','rachuig','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('lark','wise','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('laurice','aslum','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('leonore','lansley','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('libbey','blakiston','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('linet','tellenbach','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('maje','going','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('marena','girling','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('marian','jennison','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('marisa','simic','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('matelda','knowlys','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('maxi','calderwood','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('nell','gherardi','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('norean','laidlow','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('oswald','wiggall','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('otho','bunclark','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('raquela','palia','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('raven','gloves','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('rebeca','freestone','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('rebeca','rimmington','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('renee','jolliman','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('rorke','laxe','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('salvador','fontenot','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('sarette','lared','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('shane','astling','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('shela','whereat','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('sianna','skoughman','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('sigrid','goble','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('tania','pepin','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('thaxter','probbin','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('torrin','del monte','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('tremaine','mckea','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('valry','prisk','Operations') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('victoir','posnett','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('vlad','boswood','Finance') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('winslow','ugoni','Claims') GO
INSERT INTO Employees(EmployeeFirst,EmployeeLast,BusinessArea) VALUES ('wynnie','thickpenny','Operations') GO
